"""Professional TDD document renderer with QA metadata and traceability."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class ManagerAgent:
    def __init__(self, output_directory: str = "output") -> None:
        self.output_directory = Path(output_directory)
        self.output_directory.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _items(value: Any) -> list[str]:
        if isinstance(value, list):
            return [str(x).strip() for x in value if str(x).strip()]
        if value is None:
            return []
        return [str(value).strip()]

    @classmethod
    def _bullets(cls, value: Any) -> str:
        items = cls._items(value)
        return "\n".join(f"- {x}" for x in items) if items else "- Not determined from available project evidence."

    @classmethod
    def _numbered(cls, value: Any) -> str:
        items = cls._items(value)
        return "\n".join(f"{i}. {x}" for i, x in enumerate(items, 1)) if items else "1. Not determined from available project evidence."

    @staticmethod
    def _table(rows: list[tuple[str, str]]) -> str:
        out = "| Area | Evidence |\n|---|---|\n"
        for a, b in rows:
            out += f"| {a} | {b} |\n"
        return out

    def generate_tdd(self, blueprint: dict[str, Any]) -> str:
        arch = blueprint.get("architecture", {}) or {}
        qa = blueprint.get("quality_review", {}) or {}
        generated = datetime.now(timezone.utc).isoformat(timespec="seconds")

        title = blueprint.get("document_title", "Technical Design Document")
        source = blueprint.get("source_file", "Unknown")
        stats = blueprint.get("source_statistics", {})
        evidence_ids = blueprint.get("retrieved_evidence_ids", [])

        return f"""# {title}

> **Evidence-Grounded Technical Design Document**
>
> Generated by the Agentic TDD Generation Pipeline. Concrete implementation claims
> are tied to retrieved evidence IDs. Unsupported details are explicitly marked.

---

## 1. Document Control

{self._table([
    ("Source", f"`{source}`"),
    ("Generated", f"`{generated}`"),
    ("Generation mode", "Scanner → Source-aware Chunking → Hybrid Retrieval → Architect → Critic → Manager"),
    ("Evidence IDs retrieved", str(len(evidence_ids))),
    ("Quality gate", "PASS" if qa.get("passed", False) else "REVIEW REQUIRED"),
    ("Quality score", str(qa.get("score", "N/A"))),
])}

---

## 2. Executive Summary

{blueprint.get("system_overview", "Not determined from available project evidence.")}

---

## 3. Source Analysis

{self._table([
    ("Characters", str(stats.get("characters", 0))),
    ("Lines", str(stats.get("lines", 0))),
    ("Non-empty lines", str(stats.get("non_empty_lines", 0))),
    ("Files analyzed", str(blueprint.get("project_file_count", 0))),
])}

---

## 4. Project Scope

{self._bullets(blueprint.get("project_scope"))}

---

## 5. Architecture

### 5.1 Components

{self._bullets(arch.get("components"))}

### 5.2 Responsibilities

{self._bullets(arch.get("component_responsibilities"))}

### 5.3 Data Flow

{self._numbered(arch.get("data_flow"))}

### 5.4 Dependencies

{self._bullets(arch.get("dependencies"))}

---

## 6. Functional Requirements

{self._numbered(blueprint.get("functional_requirements"))}

---

## 7. Non-Functional Requirements

{self._bullets(blueprint.get("non_functional_requirements"))}

> Quantitative latency, throughput, availability, and scalability values are not
> claimed unless supported by source evidence.

---

## 8. Detailed Technical Design

{self._bullets(blueprint.get("technical_details"))}

---

## 9. API / External Integration

{self._bullets(blueprint.get("api_design"))}

---

## 10. Data and Storage

{self._bullets(blueprint.get("data_storage"))}

---

## 11. Error Handling

{self._bullets(blueprint.get("error_handling"))}

---

## 12. Security and Configuration

### Security

{self._bullets(blueprint.get("security"))}

### Configuration

{self._bullets(blueprint.get("configuration"))}

---

## 13. Testing Strategy

{self._bullets(blueprint.get("testing_strategy"))}

---

## 14. Deployment

{self._bullets(blueprint.get("deployment"))}

---

## 15. Performance

{self._bullets(blueprint.get("performance"))}

---

## 16. Quality Review

### Deterministic quality gate

{self._bullets(qa.get("issues")) if qa.get("issues") else "- No deterministic blocking issues detected."}

### Warnings

{self._bullets(qa.get("warnings")) if qa.get("warnings") else "- No quality warnings detected."}

### Suggested repairs

{self._bullets(qa.get("suggested_repairs")) if qa.get("suggested_repairs") else "- No automatic repairs suggested."}

---

## 17. Traceability

The following evidence IDs were available to the Architect Agent:

{self._bullets(evidence_ids)}

Source files of interest:

{self._bullets(blueprint.get("source_files_of_interest"))}

Evidence notes:

{self._bullets(blueprint.get("evidence_notes"))}

---

## 18. Limitations and Assumptions

{self._bullets(blueprint.get("limitations"))}

- Retrieved evidence is a subset of the complete source corpus.
- Absence of retrieved evidence is not treated as proof that a feature does not exist.
- README/comments may describe intended behavior rather than verified runtime behavior.
- This document should not claim production SLA/security/scalability without measurements.

---

## 19. Generation Pipeline

```text
Project Input
     |
     v
Deterministic Scanner
     |
     v
Source-aware Chunking + Evidence IDs
     |
     v
Hybrid Evidence Retrieval
     |
     v
Architect Agent
     |
     v
Critic / Quality Gate
     |
     v
Manager Agent
     |
     v
Traceable TDD
```

---

## 20. Document Status

**Evidence-grounded automated draft with quality-gate metadata.**

Generated at `{generated}`.
"""

    def save_tdd(self, document: str, filename: str = "technical_design_document.md") -> Path:
        path = self.output_directory / filename
        path.write_text(document, encoding="utf-8")
        return path
